### ISSUE TITLE
Definir el MVP

### ISSUE THREAD

**Issue by JoseAConcepcion** [ANJEMI/distributed-systems-project#1]

**Comment by josem-nex** [comment]
Decidir tipo de almacenamiento a usar en el Tracker, tiene que ser friendly con python

**Comment by josem-nex** [comment]
División de los archivos en chunks de 256 o 512 KB generalmente
https://www.bittorrent.org/beps/bep_0003.html

**Comment by josem-nex** [comment]
Toda la documentación del bittorrent oficial aquí: https://www.bittorrent.org/beps/bep_0000.html

**Comment by josem-nex** [comment]
Interfaz gráfica solo para Cliente (por el momento)

**Comment by josem-nex** [comment]
Definir en un principio, como seleccionar de que nodo descargar cada chunk

**Comment by josem-nex** [comment]
Simular los nodos con un filesystem por carpetas

**Comment by JoseAConcepcion** [comment]
- Decidir tipo de almacenamiento a usar en el Tracker, tiene que ser friendly con python
- Interfaz gráfica solo para Cliente (por el momento)
- Definir en un principio, como seleccionar de que nodo descargar cada chunk
- Simular los nodos con un filesystem por carpetas
- Todo lo relacionado con el .torrent
