### ISSUE TITLE
JSON tracker_data

### ISSUE THREAD

**Issue by josem-nex** [ANJEMI/distributed-systems-project#3]
Actualizar los procesamientos del JSON con los datos interiores de cada peers, en un principio: {
          "peer_id": "1",
          "ip": "",
          "port": 6881
        }

**Comment by josem-nex** [comment]
Nueva propuesta, también con posibles cambios en el futuro:
{
                        "torrent_id": "",  # Torrent ID (hash)
                        "name": "",        # File name
                        "size": 0,        # Size in bytes
                        "piece_size": 256,    # Size of each piece in bytes
                        "pieces": [],     # List of pieces (initially empty)
                        "number_pieces": 0,  # Number of pieces
                        "seeders": 0,     # Number of seeders
                        "leechers": 0,    # Number of leechers
                        "peers": []       # List of peers (initially empty)
}

Donde cada peers tiene el formato:
{
"peer_id": "1",
"ip": "0.0.0.0",
"port": 8080
}

Talvez en un futuro sea util tambien que el tracker de especificamente que pieza tiene cada peers, pero bueno por el momento no

**Comment by JoseAConcepcion** [comment]
cabron acabo de actualizar y ver esto xd yo que venia a cerrar esta vaina
ya cerre la rama y todo

**Comment by JoseAConcepcion** [comment]
Done.
